"""Add itens nos pedidos

Revision ID: 8e64c2b2ec07
Revises: 6588ca81b734
Create Date: 2025-08-07 13:27:32.366532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e64c2b2ec07'
down_revision: Union[str, Sequence[str], None] = '6588ca81b734'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
